#pragma once
#include"Core/buffer.hpp"

/// @brief Enumeration of Job type
/// 
enum class Commands { None, data, chat, push, pull, subscribe, unsubscribe, VOIP, Info, error, DEBUG};

/// @brief Job definition class
/// 
/// Jobs are Generated by the clientManager::worker(bool& work) method.  
/// 
/// ##Contains
/// 
/// the Job type @see Commands
/// 
/// Requesting Client ID
/// 
/// Raw Job data, usually serialised DataElements or chat strings
class job
{
public:

	job();
	job(const Buffer& rawJob);
	~job();

	/// @brief Method to get the Client ID of the job owner
	/// @return int ID
	const int GetID() const { return ID; }

	/// @brief Method to get the Job command
	/// @return Commands enumeration - Job type
	const Commands GetCommand() const { return command; }

	/// @brief A method to get a copy of the Jobs raw data for processing.
	/// @return Buffer of raw job data (copy)
	Buffer GetJobData() const { return data; }
	
private:
	int ID;
	Commands command;
	Buffer data;

private:
	Commands ParseCommand(const Buffer& rawJob);
	int ParseClientID(const Buffer& rawJob);
	void ParseData(const Buffer& rawJob);
};

