#pragma once
#include"Core/buffer.hpp"

/// @brief Enumeration of Job type
/// 
enum class Commands { None, data, chat, push, pull, subscribe, unsubscribe, VOIP, Info, error, DEBUG};

/// @brief Job definition class
/// 
/// Jobs are Generated by the clientManager::worker(bool& work) method.  
class job
{
public:
	int ID;
	Commands command;
	Buffer data;

	Commands getCommand(const Buffer& rawJob);
	int getClientID(const Buffer& rawJob);
	void getData(const Buffer& rawJob);


	job();
	job(const Buffer& rawJob);


	~job();
};

